// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// The API Gateway Service is the interface for managing API Gateways.
///
/// @Snippet(path: "ApiGatewayServiceQuickstart")
public final class ApiGatewayServiceClient: Clients.ApiGatewayServiceProtocol, Sendable {
  let inner: any Clients.ApiGatewayServiceStub
  let pollingErrorPolicy: any GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: any GoogleGax.PollingBackoffPolicy

  /// Creates a new `ApiGatewayServiceClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.ApiGatewayServiceStub = try Clients.ApiGatewayServiceTransport(options)
    inner = Clients.ApiGatewayServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.ApiGatewayServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Lists Gateways in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_ListGateways")
  public func listGateways(
    request: ListGatewaysRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiGatewayV1.ListGatewaysResponse {
    try await self.inner.listGateways(request: request, options: options)
  }

  /// Gets details of a single Gateway.
  ///
  /// @Snippet(path: "ApiGatewayService_GetGateway")
  public func getGateway(
    request: GetGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiGatewayV1.Gateway {
    try await self.inner.getGateway(request: request, options: options)
  }

  /// Creates a new Gateway in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_CreateGateway")
  public func createGateway(
    request: CreateGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createGateway(request: request, options: options)
  }

  /// Creates a new Gateway in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_CreateGateway")
  public func createGatewayPollingUntilDone(
    request: CreateGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws -> Gateway {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Gateway>.State in
      return try op._extractStatus(Gateway.self)
    }
    let rawOp = try await self.createGateway(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Gateway>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Updates the parameters of a single Gateway.
  ///
  /// @Snippet(path: "ApiGatewayService_UpdateGateway")
  public func updateGateway(
    request: UpdateGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateGateway(request: request, options: options)
  }

  /// Updates the parameters of a single Gateway.
  ///
  /// @Snippet(path: "ApiGatewayService_UpdateGateway")
  public func updateGatewayPollingUntilDone(
    request: UpdateGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws -> Gateway {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Gateway>.State in
      return try op._extractStatus(Gateway.self)
    }
    let rawOp = try await self.updateGateway(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Gateway>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Deletes a single Gateway.
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteGateway")
  public func deleteGateway(
    request: DeleteGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteGateway(request: request, options: options)
  }

  /// Deletes a single Gateway.
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteGateway")
  public func deleteGatewayPollingUntilDone(
    request: DeleteGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteGateway(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Lists Apis in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_ListApis")
  public func listApis(
    request: ListApisRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiGatewayV1.ListApisResponse {
    try await self.inner.listApis(request: request, options: options)
  }

  /// Gets details of a single Api.
  ///
  /// @Snippet(path: "ApiGatewayService_GetApi")
  public func getApi(
    request: GetApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiGatewayV1.Api {
    try await self.inner.getApi(request: request, options: options)
  }

  /// Creates a new Api in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_CreateApi")
  public func createApi(
    request: CreateApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createApi(request: request, options: options)
  }

  /// Creates a new Api in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_CreateApi")
  public func createApiPollingUntilDone(
    request: CreateApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> Api {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Api>.State in
      return try op._extractStatus(Api.self)
    }
    let rawOp = try await self.createApi(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Api>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Updates the parameters of a single Api.
  ///
  /// @Snippet(path: "ApiGatewayService_UpdateApi")
  public func updateApi(
    request: UpdateApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateApi(request: request, options: options)
  }

  /// Updates the parameters of a single Api.
  ///
  /// @Snippet(path: "ApiGatewayService_UpdateApi")
  public func updateApiPollingUntilDone(
    request: UpdateApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> Api {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Api>.State in
      return try op._extractStatus(Api.self)
    }
    let rawOp = try await self.updateApi(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Api>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Deletes a single Api.
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteApi")
  public func deleteApi(
    request: DeleteApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteApi(request: request, options: options)
  }

  /// Deletes a single Api.
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteApi")
  public func deleteApiPollingUntilDone(
    request: DeleteApiRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteApi(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Lists ApiConfigs in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_ListApiConfigs")
  public func listApiConfigs(
    request: ListApiConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiGatewayV1.ListApiConfigsResponse {
    try await self.inner.listApiConfigs(request: request, options: options)
  }

  /// Gets details of a single ApiConfig.
  ///
  /// @Snippet(path: "ApiGatewayService_GetApiConfig")
  public func getApiConfig(
    request: GetApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiGatewayV1.ApiConfig {
    try await self.inner.getApiConfig(request: request, options: options)
  }

  /// Creates a new ApiConfig in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_CreateApiConfig")
  public func createApiConfig(
    request: CreateApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createApiConfig(request: request, options: options)
  }

  /// Creates a new ApiConfig in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_CreateApiConfig")
  public func createApiConfigPollingUntilDone(
    request: CreateApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> ApiConfig {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ApiConfig>.State in
      return try op._extractStatus(ApiConfig.self)
    }
    let rawOp = try await self.createApiConfig(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<ApiConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Updates the parameters of a single ApiConfig.
  ///
  /// @Snippet(path: "ApiGatewayService_UpdateApiConfig")
  public func updateApiConfig(
    request: UpdateApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateApiConfig(request: request, options: options)
  }

  /// Updates the parameters of a single ApiConfig.
  ///
  /// @Snippet(path: "ApiGatewayService_UpdateApiConfig")
  public func updateApiConfigPollingUntilDone(
    request: UpdateApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> ApiConfig {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<ApiConfig>.State in
      return try op._extractStatus(ApiConfig.self)
    }
    let rawOp = try await self.updateApiConfig(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<ApiConfig>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    return try await poller.wait()
  }

  /// Deletes a single ApiConfig.
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteApiConfig")
  public func deleteApiConfig(
    request: DeleteApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteApiConfig(request: request, options: options)
  }

  /// Deletes a single ApiConfig.
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteApiConfig")
  public func deleteApiConfigPollingUntilDone(
    request: DeleteApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteApiConfig(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    let poller = GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
    try await poller.wait()
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiGatewayService_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiGatewayService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiGatewayService_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiGatewayService_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `ApiGatewayServiceClient`.
  ///
  /// To mock `ApiGatewayServiceClient` change your functions to receive
  /// `some ApiGatewayServiceProtocol` or `any ApiGatewayServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol ApiGatewayServiceProtocol: Sendable {
    /// See `ApiGatewayServiceClient.listGateways`.
    func listGateways(
      request: ListGatewaysRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiGatewayV1.ListGatewaysResponse

    /// See `ApiGatewayServiceClient.getGateway`.
    func getGateway(
      request: GetGatewayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiGatewayV1.Gateway

    /// See `ApiGatewayServiceClient.createGateway`.
    func createGateway(
      request: CreateGatewayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiGatewayServiceClient.createGateway`.
    func createGatewayPollingUntilDone(
      request: CreateGatewayRequest, options: GoogleGax.RequestOptions
    ) async throws -> Gateway

    /// See `ApiGatewayServiceClient.updateGateway`.
    func updateGateway(
      request: UpdateGatewayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiGatewayServiceClient.updateGateway`.
    func updateGatewayPollingUntilDone(
      request: UpdateGatewayRequest, options: GoogleGax.RequestOptions
    ) async throws -> Gateway

    /// See `ApiGatewayServiceClient.deleteGateway`.
    func deleteGateway(
      request: DeleteGatewayRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiGatewayServiceClient.deleteGateway`.
    func deleteGatewayPollingUntilDone(
      request: DeleteGatewayRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiGatewayServiceClient.listApis`.
    func listApis(
      request: ListApisRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiGatewayV1.ListApisResponse

    /// See `ApiGatewayServiceClient.getApi`.
    func getApi(
      request: GetApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiGatewayV1.Api

    /// See `ApiGatewayServiceClient.createApi`.
    func createApi(
      request: CreateApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiGatewayServiceClient.createApi`.
    func createApiPollingUntilDone(
      request: CreateApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> Api

    /// See `ApiGatewayServiceClient.updateApi`.
    func updateApi(
      request: UpdateApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiGatewayServiceClient.updateApi`.
    func updateApiPollingUntilDone(
      request: UpdateApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> Api

    /// See `ApiGatewayServiceClient.deleteApi`.
    func deleteApi(
      request: DeleteApiRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiGatewayServiceClient.deleteApi`.
    func deleteApiPollingUntilDone(
      request: DeleteApiRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiGatewayServiceClient.listApiConfigs`.
    func listApiConfigs(
      request: ListApiConfigsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiGatewayV1.ListApiConfigsResponse

    /// See `ApiGatewayServiceClient.getApiConfig`.
    func getApiConfig(
      request: GetApiConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudApiGatewayV1.ApiConfig

    /// See `ApiGatewayServiceClient.createApiConfig`.
    func createApiConfig(
      request: CreateApiConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiGatewayServiceClient.createApiConfig`.
    func createApiConfigPollingUntilDone(
      request: CreateApiConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> ApiConfig

    /// See `ApiGatewayServiceClient.updateApiConfig`.
    func updateApiConfig(
      request: UpdateApiConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiGatewayServiceClient.updateApiConfig`.
    func updateApiConfigPollingUntilDone(
      request: UpdateApiConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> ApiConfig

    /// See `ApiGatewayServiceClient.deleteApiConfig`.
    func deleteApiConfig(
      request: DeleteApiConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `ApiGatewayServiceClient.deleteApiConfig`.
    func deleteApiConfigPollingUntilDone(
      request: DeleteApiConfigRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiGatewayServiceClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `ApiGatewayServiceClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws

    /// See `ApiGatewayServiceClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.ApiGatewayServiceProtocol {
  public func listGateways(request: ListGatewaysRequest) async throws
    -> GoogleCloudApiGatewayV1.ListGatewaysResponse
  {
    try await self.listGateways(request: request, options: .init())
  }

  public func listGateways(
    request: ListGatewaysRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiGatewayV1.ListGatewaysResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listGatewaysByItems(
    request: ListGatewaysRequest
  ) -> some AsyncSequence<Gateway, any Swift.Error> & Sendable {
    self.listGatewaysByItems(request: request, options: .init())
  }

  /// Lists Gateways in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_ListGateways")
  public func listGatewaysByItems(
    request: ListGatewaysRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Gateway, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudApiGatewayV1.ListGatewaysResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listGateways(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listGatewaysByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Gateway, any Swift.Error> & Sendable {
    let request = ListGatewaysRequest().with {
      $0.parent = parent
    }
    return self.listGatewaysByItems(request: request)
  }

  public func getGateway(request: GetGatewayRequest) async throws -> GoogleCloudApiGatewayV1.Gateway
  {
    try await self.getGateway(request: request, options: .init())
  }

  public func getGateway(
    request: GetGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiGatewayV1.Gateway {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getGateway(
    name: Swift.String,
  ) async throws -> GoogleCloudApiGatewayV1.Gateway {
    let request = GetGatewayRequest().with {
      $0.name = name
    }
    return try await self.getGateway(request: request)
  }

  public func createGateway(request: CreateGatewayRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createGateway(request: request, options: .init())
  }

  public func createGateway(
    request: CreateGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createGatewayPollingUntilDone(request: CreateGatewayRequest) async throws -> Gateway {
    return try await self.createGatewayPollingUntilDone(request: request, options: .init())
  }

  public func createGatewayPollingUntilDone(
    request: CreateGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws -> Gateway {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createGatewayPollingUntilDone(
    parent: Swift.String,
    gateway: Gateway?,
    gatewayId: Swift.String,
  ) async throws -> Gateway {
    let request = CreateGatewayRequest().with {
      $0.parent = parent
      $0.gateway = gateway
      $0.gatewayId = gatewayId
    }
    return try await self.createGatewayPollingUntilDone(request: request)
  }

  public func updateGateway(request: UpdateGatewayRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateGateway(request: request, options: .init())
  }

  public func updateGateway(
    request: UpdateGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateGatewayPollingUntilDone(request: UpdateGatewayRequest) async throws -> Gateway {
    return try await self.updateGatewayPollingUntilDone(request: request, options: .init())
  }

  public func updateGatewayPollingUntilDone(
    request: UpdateGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws -> Gateway {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateGatewayPollingUntilDone(
    gateway: Gateway?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> Gateway {
    let request = UpdateGatewayRequest().with {
      $0.gateway = gateway
      $0.updateMask = updateMask
    }
    return try await self.updateGatewayPollingUntilDone(request: request)
  }

  public func deleteGateway(request: DeleteGatewayRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteGateway(request: request, options: .init())
  }

  public func deleteGateway(
    request: DeleteGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteGatewayPollingUntilDone(request: DeleteGatewayRequest) async throws {
    try await self.deleteGatewayPollingUntilDone(request: request, options: .init())
  }

  public func deleteGatewayPollingUntilDone(
    request: DeleteGatewayRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteGatewayPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteGatewayRequest().with {
      $0.name = name
    }
    try await self.deleteGatewayPollingUntilDone(request: request)
  }

  public func listApis(request: ListApisRequest) async throws
    -> GoogleCloudApiGatewayV1.ListApisResponse
  {
    try await self.listApis(request: request, options: .init())
  }

  public func listApis(
    request: ListApisRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiGatewayV1.ListApisResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listApisByItems(
    request: ListApisRequest
  ) -> some AsyncSequence<Api, any Swift.Error> & Sendable {
    self.listApisByItems(request: request, options: .init())
  }

  /// Lists Apis in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_ListApis")
  public func listApisByItems(
    request: ListApisRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<Api, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudApiGatewayV1.ListApisResponse in
      var request = request
      request.pageToken = token
      return try await self.listApis(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listApisByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<Api, any Swift.Error> & Sendable {
    let request = ListApisRequest().with {
      $0.parent = parent
    }
    return self.listApisByItems(request: request)
  }

  public func getApi(request: GetApiRequest) async throws -> GoogleCloudApiGatewayV1.Api {
    try await self.getApi(request: request, options: .init())
  }

  public func getApi(
    request: GetApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiGatewayV1.Api {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getApi(
    name: Swift.String,
  ) async throws -> GoogleCloudApiGatewayV1.Api {
    let request = GetApiRequest().with {
      $0.name = name
    }
    return try await self.getApi(request: request)
  }

  public func createApi(request: CreateApiRequest) async throws -> GoogleLongRunning.Operation {
    try await self.createApi(request: request, options: .init())
  }

  public func createApi(
    request: CreateApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createApiPollingUntilDone(request: CreateApiRequest) async throws -> Api {
    return try await self.createApiPollingUntilDone(request: request, options: .init())
  }

  public func createApiPollingUntilDone(
    request: CreateApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> Api {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createApiPollingUntilDone(
    parent: Swift.String,
    api: Api?,
    apiId: Swift.String,
  ) async throws -> Api {
    let request = CreateApiRequest().with {
      $0.parent = parent
      $0.api = api
      $0.apiId = apiId
    }
    return try await self.createApiPollingUntilDone(request: request)
  }

  public func updateApi(request: UpdateApiRequest) async throws -> GoogleLongRunning.Operation {
    try await self.updateApi(request: request, options: .init())
  }

  public func updateApi(
    request: UpdateApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateApiPollingUntilDone(request: UpdateApiRequest) async throws -> Api {
    return try await self.updateApiPollingUntilDone(request: request, options: .init())
  }

  public func updateApiPollingUntilDone(
    request: UpdateApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> Api {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateApiPollingUntilDone(
    api: Api?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> Api {
    let request = UpdateApiRequest().with {
      $0.api = api
      $0.updateMask = updateMask
    }
    return try await self.updateApiPollingUntilDone(request: request)
  }

  public func deleteApi(request: DeleteApiRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteApi(request: request, options: .init())
  }

  public func deleteApi(
    request: DeleteApiRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteApiPollingUntilDone(request: DeleteApiRequest) async throws {
    try await self.deleteApiPollingUntilDone(request: request, options: .init())
  }

  public func deleteApiPollingUntilDone(
    request: DeleteApiRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteApiPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteApiRequest().with {
      $0.name = name
    }
    try await self.deleteApiPollingUntilDone(request: request)
  }

  public func listApiConfigs(request: ListApiConfigsRequest) async throws
    -> GoogleCloudApiGatewayV1.ListApiConfigsResponse
  {
    try await self.listApiConfigs(request: request, options: .init())
  }

  public func listApiConfigs(
    request: ListApiConfigsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiGatewayV1.ListApiConfigsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listApiConfigsByItems(
    request: ListApiConfigsRequest
  ) -> some AsyncSequence<ApiConfig, any Swift.Error> & Sendable {
    self.listApiConfigsByItems(request: request, options: .init())
  }

  /// Lists ApiConfigs in a given project and location.
  ///
  /// @Snippet(path: "ApiGatewayService_ListApiConfigs")
  public func listApiConfigsByItems(
    request: ListApiConfigsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<ApiConfig, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleCloudApiGatewayV1.ListApiConfigsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.listApiConfigs(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listApiConfigsByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<ApiConfig, any Swift.Error> & Sendable {
    let request = ListApiConfigsRequest().with {
      $0.parent = parent
    }
    return self.listApiConfigsByItems(request: request)
  }

  public func getApiConfig(request: GetApiConfigRequest) async throws
    -> GoogleCloudApiGatewayV1.ApiConfig
  {
    try await self.getApiConfig(request: request, options: .init())
  }

  public func getApiConfig(
    request: GetApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleCloudApiGatewayV1.ApiConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getApiConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudApiGatewayV1.ApiConfig {
    let request = GetApiConfigRequest().with {
      $0.name = name
    }
    return try await self.getApiConfig(request: request)
  }

  public func createApiConfig(request: CreateApiConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createApiConfig(request: request, options: .init())
  }

  public func createApiConfig(
    request: CreateApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createApiConfigPollingUntilDone(request: CreateApiConfigRequest) async throws
    -> ApiConfig
  {
    return try await self.createApiConfigPollingUntilDone(request: request, options: .init())
  }

  public func createApiConfigPollingUntilDone(
    request: CreateApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> ApiConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createApiConfigPollingUntilDone(
    parent: Swift.String,
    apiConfig: ApiConfig?,
    apiConfigId: Swift.String,
  ) async throws -> ApiConfig {
    let request = CreateApiConfigRequest().with {
      $0.parent = parent
      $0.apiConfig = apiConfig
      $0.apiConfigId = apiConfigId
    }
    return try await self.createApiConfigPollingUntilDone(request: request)
  }

  public func updateApiConfig(request: UpdateApiConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateApiConfig(request: request, options: .init())
  }

  public func updateApiConfig(
    request: UpdateApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateApiConfigPollingUntilDone(request: UpdateApiConfigRequest) async throws
    -> ApiConfig
  {
    return try await self.updateApiConfigPollingUntilDone(request: request, options: .init())
  }

  public func updateApiConfigPollingUntilDone(
    request: UpdateApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> ApiConfig {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateApiConfigPollingUntilDone(
    apiConfig: ApiConfig?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> ApiConfig {
    let request = UpdateApiConfigRequest().with {
      $0.apiConfig = apiConfig
      $0.updateMask = updateMask
    }
    return try await self.updateApiConfigPollingUntilDone(request: request)
  }

  public func deleteApiConfig(request: DeleteApiConfigRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteApiConfig(request: request, options: .init())
  }

  public func deleteApiConfig(
    request: DeleteApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteApiConfigPollingUntilDone(request: DeleteApiConfigRequest) async throws {
    try await self.deleteApiConfigPollingUntilDone(request: request, options: .init())
  }

  public func deleteApiConfigPollingUntilDone(
    request: DeleteApiConfigRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteApiConfigPollingUntilDone(
    name: Swift.String,
  ) async throws {
    let request = DeleteApiConfigRequest().with {
      $0.name = name
    }
    try await self.deleteApiConfigPollingUntilDone(request: request)
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest
  ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
    self.listOperationsByItems(request: request, options: .init())
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "ApiGatewayService_ListOperations")
  public func listOperationsByItems(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = request
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(
      listRpc: listRpc, initialPageToken: request.pageToken)
  }

  public func listOperationsByItems(
    name: Swift.String,
    filter: Swift.String,
  ) -> some AsyncSequence<GoogleLongRunning.Operation, any Swift.Error> & Sendable {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return self.listOperationsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
  ) async throws {
    throw GoogleGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
